Repository smaranjitghose/DocLense, pull requests merged in 2020-12, with the labels that each got.

#7 Fixed App Crash bug on iOS
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/Info.plist
Labels: DWOC, PR: reviewed-approved

#8 Improved Docs
  README.md
  imgs/Dart_logo.png
  imgs/flutter.png
Labels: DWOC

#11 Enhanced the Undo Button functionality
  lib/Imageview.dart
  pubspec.lock
Labels: DWOC, Level-4

#17 pubspec.yaml Issue
  pubspec.yaml
Labels: PR: unreviewed
