Repository smaranjitghose/DocLense, pull requests merged in 2021-03, with the labels that each got.

#151 The rename option is now compatible with the starred documents feature
  lib/Home.dart
Labels: PR: unreviewed

#150 Fixed the issue associated with build failing
  pubspec.lock
  pubspec.yaml
Labels: PR: reviewed-approved

#153 Enhancement: Updated the PDF display card
  lib/Home.dart
Labels: CrossWOC, GSSOC21, Level2, PR: reviewed-approved

#158 add lint rules and github actions
  .github/workflows/ci.yml
  .gitignore
  analysis_options.yaml
  pubspec.lock
  pubspec.yaml
Labels: PR: unreviewed

#162 refactor deprecated widgets and methods
  lib/Filterview.dart
  lib/Home.dart
  lib/Imageview.dart
  lib/Providers/ImageList.dart
  lib/StarredDocuments.dart
  lib/multi_select_delete.dart
Labels: GSSOC21, PR: reviewed-approved

#155 For #154 Padding issue fixed and reduced repeated code
  lib/setting_text.dart
  lib/settings.dart
Labels: GSSOC21, PR: reviewed-approved

#167 refactor : lint errors fixes
  analysis_options.yaml
  lib/About.dart
  lib/Constants/ThemeConstants.dart
  lib/Filterview.dart
  lib/Home.dart
  lib/Imageview.dart
  lib/MainDrawer.dart
  lib/PDFConversion.dart
  lib/PDFPreviewScreen.dart
  lib/Providers/ImageList.dart
  lib/Providers/ThemeProvider.dart
  lib/Services/SearchService.dart
  lib/Services/SharedPreferences.dart
  lib/StarredDocuments.dart
  lib/griditem.dart
  lib/main.dart
  lib/multi_select_delete.dart
  lib/settings.dart
Labels: Level3, PR: unreviewed, gssoc21

#169 Feature: Implemented Date of creation of PDF
  lib/Home.dart
  lib/PDFConversion.dart
  lib/Services/SearchService.dart
  lib/StarredDocuments.dart
  lib/multi_select_delete.dart
  lib/setting_text.dart
  lib/settings.dart
Labels: Level-4, PR: reviewed-approved, PR: reviewed-changes-requested

#166 Fix #163 : Pixel Overflow in Bottom Toolbar
  lib/Imageview.dart
Labels: Level2, PR: reviewed-approved, PR: unreviewed, gssoc21

#179 Reformated the Rating dialogue
  lib/MainDrawer.dart
Labels: Level2, PR: reviewed-approved, gssoc21

#173 Removed borders from pdf
  lib/PDFConversion.dart
  pubspec.lock
  pubspec.lock.old
Labels: Level3, PR: partially-approved, gssoc21

#182 fix(Imageview.dart): Syntax Error Issue #181
  lib/Imageview.dart
Labels: Level0, PR: reviewed-approved, PR: reviewed-changes-requested, PR: unreviewed

#187 Feature: Bug Report
  lib/Imageview.dart
  lib/main.dart
  lib/settings.dart
  pubspec.lock
  pubspec.yaml
Labels: PR: unreviewed

#198 Ratioed the GridImage size
  lib/griditem.dart
Labels: PR: unreviewed

#202 text input issues fixed
  lib/Home.dart
  lib/PDFConversion.dart
  lib/Services/SearchService.dart
Labels: PR: reviewed-approved

#207 Changed the all icons color in home.dart
  lib/Constants/theme_constants.dart
  lib/Providers/image_list.dart
  lib/Providers/theme_provider.dart
  lib/Services/search_service.dart
  lib/Services/shared_preferences.dart
  lib/about.dart
  lib/filter_view.dart
  lib/home.dart
  lib/image_view.dart
  lib/main.dart
  lib/main_drawer.dart
  lib/multi_select_delete.dart
  lib/pdf_conversion.dart
  lib/pdf_preview_screen.dart
  lib/settings.dart
  lib/starred_documents.dart
Labels: PR: unreviewed

#206 Solved package issue
  pubspec.lock
  pubspec.yaml
Labels: PR: unreviewed

#195 Added image preview to PDF card in home screen
  lib/home.dart
  lib/pdf_conversion.dart
Labels: PR: unreviewed

#205 made home screen responsive for small screen sizes
  lib/home.dart
Labels: PR: unreviewed

#213 Refactored Drawer ListTile Widget
  lib/UI Components/drawer_nav_item.dart
  lib/about.dart
  lib/home.dart
  lib/main.dart
  lib/main_drawer.dart
  pubspec.lock
Labels: PR: unreviewed

#217 Removed all the unnecessary details
  lib/settings.dart
  pubspec.lock
Labels: Level2, PR: reviewed-approved, gssoc21

#215 Reformated the starred PDF card
  lib/Models/preferences.dart
  lib/Models/preferences.g.dart
  lib/home.dart
  lib/starred_documents.dart
Labels: PR: unreviewed

#222 Fixed the pdf cards.
  lib/home.dart
  lib/pdf_conversion.dart
Labels: PR: unreviewed

#214 settings : contact developers screen
  assets/images/team/anush_bhatia.png
  assets/images/team/smaranjit_ghose.png
  lib/home.dart
  lib/main_drawer.dart
  lib/settings/contact_developers.dart
  lib/settings/setting_text.dart
  lib/settings/settings.dart
  pubspec.yaml
Labels: Level-2, PR: unreviewed

#211 Fixed renderflex overflow in the bottom nav bar
  lib/filter_view.dart
  lib/image_view.dart
Labels: Level-1, PR: unreviewed

#219 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Level0, PR: unreviewed

#224 Starred docs pdf card overflow fixed
  lib/starred_documents.dart
Labels: PR: unreviewed

#234 Fixes Minor bug in rating card dark mode #180
  lib/main_drawer.dart
Labels: Level0, PR: reviewed-approved

#233 fixes # 232
  lib/home.dart
Labels: Level0, PR: reviewed-approved

#235 Camera Modified.... Now App Not Crash after taking Image
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/values-night/styles.xml
  lib/home.dart
  lib/multi_select_delete.dart
  lib/pdf_conversion.dart
  lib/pdf_preview_screen.dart
  lib/starred_documents.dart
  pubspec.yaml
Labels: PR: unreviewed

#238 Modifies Readme.md file
  README.md
Labels: Level0, PR: reviewed-approved, gssoc21

#236 Fixed the bug associated with moving a PDF to another directory
  android/app/src/main/AndroidManifest.xml
  lib/home.dart
Labels: PR: unreviewed

#237 UI changes for starred document card
  lib/starred_documents.dart
Labels: PR: unreviewed

#243 Feature: store images as strings in the Hive box
  lib/about.dart
  lib/constants/theme_constants.dart
  lib/filter_view.dart
  lib/home.dart
  lib/image_view.dart
  lib/main_drawer.dart
  lib/models/preferences.dart
  lib/models/preferences.g.dart
  lib/multi_select_delete.dart
  lib/pdf_conversion.dart
  lib/providers/image_list.dart
  lib/providers/theme_provider.dart
  lib/services/search_service.dart
  lib/services/shared_preferences.dart
  lib/settings/settings.dart
  lib/starred_documents.dart
  lib/utils/image_converter.dart
  pubspec.lock
Labels: PR: unreviewed

#241 Integrated starring feature with changing directory feature
  lib/home.dart
Labels: PR: unreviewed
