Repository smaranjitghose/DocLense, pull requests merged in 2021-01, with the labels that each got.

#16 Added Logo and Splashscreen.
  assets/images/doclense.png
  assets/images/logo scanning.gif
  assets/images/logo.png
  assets/images/logos.png
  assets/images/scanlogo.png
  lib/About.dart
  lib/MainDrawer.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: DWOC, Level-5, PR: reviewed-changes-requested, PR: unreviewed

#20 Camera Based Scanner
  android/app/src/main/AndroidManifest.xml
  lib/Home.dart
  pubspec.lock
  pubspec.yaml
Labels: PR: unreviewed

#28 Created Contributing.md
  CONTRIBUTING.md
Labels: Easy, SWoC2021

#48 Added a minimalistic settings screen ui
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/MainDrawer.dart
  lib/settings.dart
  pubspec.lock
Labels: PR: unreviewed

#51 Added Options to Choose Directory to save the pdf
  lib/PDFConversion.dart
  pubspec.lock
  pubspec.yaml
Labels: PR: reviewed-approved

#52 Feature/long press
  .vscode/launch.json
  android/app/src/main/res/drawable/info.png
  android/app/src/main/res/drawable/setting.png
  android/app/src/main/res/drawable/starred.png
  lib/Home.dart
  lib/Imageview.dart
  lib/MainDrawer.dart
  pubspec.lock
  pubspec.yaml
Labels: PR: unreviewed
