Repository smaranjitghose/DocLense, pull requests merged in 2021-02, with the labels that each got.

#55 Added Option to share app
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/MainDrawer.dart
  pubspec.lock
  pubspec.yaml
Labels: DWOC, Level-4, PR: reviewed-approved

#69 Added Feature to save and display pdfs on homescreen
  lib/Home.dart
  lib/PDFConversion.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: DWOC, Level-5, PR: reviewed-approved

#70 appRatingAdded
  lib/MainDrawer.dart
  pubspec.lock
  pubspec.yaml
Labels: PR: unreviewed

#76 Added FadeTransition animation whenever a page is pushed
  lib/MainDrawer.dart
Labels: PR: unreviewed

#75 Fixed the console error in Imageview.dart
  lib/Filterview.dart
  lib/Imageview.dart
Labels: MWOC, PR: reviewed-approved, PR: unreviewed

#78 installationTimeReduced
  lib/SplashScreen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: PR: unreviewed

#79 Feature/full screen pdf
  lib/Imageview.dart
  lib/main.dart
Labels: PR: unreviewed

#80 Added Onboarding screen
  assets/images/scan.jpg
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: PR: unreviewed

#87 [fix] Documentation
  README.md
Labels: PR: reviewed-approved

#81 Implemented dark theme
  assets/images/doclenseDarkCropped.jpg
  assets/images/doclenselight.svg
  lib/About.dart
  lib/Constants/ThemeConstants.dart
  lib/Filterview.dart
  lib/Home.dart
  lib/Imageview.dart
  lib/MainDrawer.dart
  lib/PDFConversion.dart
  lib/Providers/ThemeProvider.dart
  lib/Services/SharedPreferences.dart
  lib/main.dart
  lib/multi_select_delete.dart
  lib/settings.dart
Labels: PR: unreviewed

#90 Revert "Implemented dark theme"
  assets/doclenselight.svg
  assets/images/doclenseDarkCropped.jpg
  lib/About.dart
  lib/Constants/ThemeConstants.dart
  lib/Filterview.dart
  lib/Home.dart
  lib/Imageview.dart
  lib/MainDrawer.dart
  lib/PDFConversion.dart
  lib/Providers/ThemeProvider.dart
  lib/Services/SharedPreferences.dart
  lib/main.dart
  lib/multi_select_delete.dart
  lib/settings.dart
Labels: PR: unreviewed

#91 Fixed styling issues in all files, minor change 1
  lib/About.dart
  lib/Home.dart
  lib/PDFConversion.dart
  lib/griditem.dart
  lib/main.dart
  lib/multi_select_delete.dart
  lib/settings.dart
Labels: PR: unreviewed

#92 Deleted unnecessary imports and TODOs, minor change 2
  lib/Home.dart
  lib/Imageview.dart
  lib/settings.dart
Labels: PR: unreviewed

#93 Fixed image size issue in Imageview.dart
  lib/Imageview.dart
Labels: PR: unreviewed

#96 Revert "Revert "Implemented dark theme""
  assets/images/doclenseDarkCropped.jpg
  assets/images/doclenselight.svg
  lib/About.dart
  lib/Constants/ThemeConstants.dart
  lib/Filterview.dart
  lib/Home.dart
  lib/Imageview.dart
  lib/MainDrawer.dart
  lib/PDFConversion.dart
  lib/Providers/ThemeProvider.dart
  lib/Services/SharedPreferences.dart
  lib/main.dart
  lib/multi_select_delete.dart
  lib/settings.dart
Labels: PR: unreviewed

#95 Fixed the issue with app crashing on pressing the crop button
  android/app/src/main/AndroidManifest.xml
  lib/Imageview.dart
Labels: PR: unreviewed

#102 Replaced all PNGs with SVGs
  assets/doclenselightsmall.svg
  assets/doclensewhite.svg
  assets/doclensewhitesmall.svg
  assets/images/doclenselight.svg
  lib/About.dart
  lib/MainDrawer.dart
  lib/main.dart
  pubspec.yaml
Labels: PR: unreviewed

#106 Clicking the back button from PDF now redirects the user to Home screen
  lib/PDFPreviewScreen.dart
Labels: PR: unreviewed

#105 Redesigned Main Drawer
  lib/MainDrawer.dart
Labels: PR: unreviewed

#101 Migrate Local Storage to HiveDB
  lib/Home.dart
  lib/Models/preferences.dart
  lib/Models/preferences.g.dart
  lib/PDFConversion.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: PR: unreviewed

#111 Fixed all the small issues in the app
  lib/Home.dart
  lib/Imageview.dart
  lib/PDFConversion.dart
Labels: PR: unreviewed

#116 Fixed the issue with endless stacking of screens
  lib/Home.dart
  lib/MainDrawer.dart
  lib/PDFPreviewScreen.dart
  lib/multi_select_delete.dart
Labels: PR: unreviewed

#115 Added background SVGs and illustrations in About us page
  assets/aboutPage/bg-inward-deep.svg
  assets/aboutPage/bg-inward.svg
  assets/aboutPage/bg-outward.svg
  assets/aboutPage/bg-wave.svg
  assets/aboutPage/curve.svg
  assets/aboutPage/curve2.svg
  assets/aboutPage/curvelight.svg
  assets/aboutPage/undraw_At_work_re_qotl.svg
  assets/aboutPage/undraw_Upload_re_pasx.svg
  lib/About.dart
  pubspec.yaml
Labels: PR: partially-approved

#119 Fixed the bug associated with deleting images
  lib/multi_select_delete.dart
Labels: PR: unreviewed

#121 Added sharing a single PDF from home page functionality
  lib/Home.dart
Labels: PR: unreviewed

#123 Fixed the bug associated with going back without clicking a picture in multi_select_delete page
  lib/multi_select_delete.dart
Labels: PR: unreviewed

#128 Improvement in README.md
  README.md
  assets/appMockups/aboutApp.png
  assets/appMockups/cropScreen-filterScreen-filterView-multiSelectScreen-pdfNameScreen.png
  assets/appMockups/cropScreen.png
  assets/appMockups/filterScreen.png
  assets/appMockups/filterView.png
  assets/appMockups/homeScreen-mainDrawer-settings-aboutApp-reviewDialogue.png
  assets/appMockups/homeScreen.png
  assets/appMockups/mainDrawer.png
  assets/appMockups/multiSelectScreen.png
  assets/appMockups/pdfNameScreen.png
  assets/appMockups/reviewDialogue.png
  assets/appMockups/settings.png
Labels: DWOC, MWOC, PR: unreviewed

#127 Fixed the issue with Intro slider appearing again and again for first time users
  lib/main.dart
Labels: PR: unreviewed

#130 Fixed the bug associated with infinite duplicating of pictures in multi_select_delete page
  lib/multi_select_delete.dart
Labels: PR: unreviewed

#137 Fixed the bug associated with images not getting discarded even after the PDF is created
  lib/PDFConversion.dart
  lib/multi_select_delete.dart
Labels: PR: unreviewed

#132 Added starred documents screen and starring functionality
  lib/Home.dart
  lib/MainDrawer.dart
  lib/PDFConversion.dart
  lib/StarredDocuments.dart
  lib/main.dart
Labels: PR: unreviewed

#135 Added delete, rename and move functionalities
  android/app/src/main/AndroidManifest.xml
  lib/Home.dart
  pubspec.lock
  pubspec.yaml
Labels: CrossWOC, Hard, PR: reviewed-approved, PR: unreviewed

#140 Fixed the delete button
  lib/Home.dart
Labels: MWOC, PR: reviewed-approved, user=Saransh-cpp:score=100

#143 Minor code fixes
  lib/Home.dart
  lib/MainDrawer.dart
  lib/Services/SearchService.dart
  lib/main.dart
Labels: PR: unreviewed

#141 Implemented the un-starring feature
  lib/Home.dart
  lib/StarredDocuments.dart
Labels: PR: unreviewed

#144 Fixed the bug associated with PDFs not getting removed from the Hive box even after deletion
  lib/Home.dart
Labels: PR: unreviewed

#146 Fixed the bug associated with rename dialogue
  lib/Home.dart
Labels: PR: unreviewed
