Repository smaranjitghose/DocLense, pull requests merged in 2021-06, with the labels that each got.

#270 Update README.md
  README.md
Labels: LGMSOC21, PR: reviewed-approved, 🟩 Level1

#279 Update README.md
  README.md
Labels: LGMSOC21, 🟪 Level0

#280 Adding margin in right and folder icon in place of text
  lib/pdf_conversion.dart
Labels: PR: unreviewed

#277 CHANGELOG.md
  CHANGELOG.md
Labels: LGMSOC21, PR: reviewed-approved, 🟩 Level1
